name: Dependabot Pull Request Approve and Merge

on:
  pull_request:
    # Default types + 'auto_merge_disabled'.
    # This allows Dependabot PRs to be automatically merged even if the target branch is updated after auto-merge has been enabled.
    types: [opened, synchronize, reopened, auto_merge_disabled]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Makes sure it's a dependabot PR.
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Echo previous version'
        run: echo "$PREV_VERSION"
        env:
          PREV_VERSION: ${{ steps.dependabot-metadata.outputs.previous-version }}

      # Only auto-approve minor and patch versions.
      - name: Approve PR
        if: |
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' 
          && !startsWith(steps.dependabot-metadata.outputs.previous-version, '0')
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT_PR_READ_WRITE }}

      # Only enable auto-merge for minor and patch versions.
      - name: Enable auto-merge for Dependabot PRs
        if: |
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' 
          && !startsWith(steps.dependabot-metadata.outputs.previous-version, '0')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT_PR_READ_WRITE }}
